### PR TITLE
Stream Error Handling

### PR DESCRIPTION
**Pull request by joshdadswellijyi**
Handle Argument exception thrown by line parser and bubble them up through an IObsevable

### CODE REVIEW

**Comment by idg10** [comment]
I may be missing something, but I'm not sure this addresses one of the points in #141:

> if we're recording all incoming messages, it may be useful to include incomplete/corrupt ones, because manual inspection might be able to infer something from the data

In addition to the error, I was envisaging the faulty line itself being supplied, so that its content could still be recorded if desired. Is that possible with this?

**Comment by joshdadswellijyi** [comment]
I could not see a "simple" way of implementing that, does that missing feature prevent this PR from progressing? If so I would suggest you take my code and extend as required.

**Comment by joshdadswellijyi** [comment]
Thanks that looks great I have merged it in.

**Comment by idg10** [comment]
Right, thanks for that. I'll bump the minor version since this is a new feature, and then kick off a release

**Comment by joshdadswellijyi** [comment]
@idg10 Thanks very much also using this preview and is working perfectly as intended 👍

**Comment by idg10** [comment]
Good to hear - thanks for letting me know, and thanks for the PR!

**Pull request merged**
